# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 862f8d37833f2c73c041f744c7583d1b642707f86954c3ba2202a35185e4ad00eef4550d4d51e4ab9b2880a77513df713a8b4ac8d332576a06f12bb83190f4b2

test:
  secret_key_base: b2cab2b05179187c6a8694b7a05e26ca60958fe8ccb9eb94e014a0eef860cf3f05d32c455141a48be3dccf305249046974a6fb7e5a8e47b03e96a066a58f3e0f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
